use color_contrast::{
    contrast_apca_from_luminance, contrast_delta_phi, contrast_lstar, contrast_michelson,
    contrast_wcag21, contrast_weber,
};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Wcag21Case {
    y1: f64,
    y2: f64,
    expect: f64,
}

#[derive(Debug, Deserialize)]
struct MichelsonCase {
    y1: f64,
    y2: f64,
    expect: f64,
}

#[derive(Debug, Deserialize)]
struct WeberCase {
    y1: f64,
    y2: f64,
    expect: f64,
}

#[derive(Debug, Deserialize)]
struct LstarCase {
    l1: f64,
    l2: f64,
    expect: f64,
}

#[derive(Debug, Deserialize)]
struct DeltaPhiCase {
    l1: f64,
    l2: f64,
    expect: f64,
}

#[derive(Debug, Deserialize)]
struct ApcaCase {
    y_bg: f64,
    y_txt: f64,
    expect: f64,
}

#[derive(Debug, Deserialize)]
struct Fixtures {
    wcag21: Vec<Wcag21Case>,
    michelson: Vec<MichelsonCase>,
    weber: Vec<WeberCase>,
    lstar: Vec<LstarCase>,
    delta_phi: Vec<DeltaPhiCase>,
    apca: Vec<ApcaCase>,
}

fn fixtures() -> Fixtures {
    // This file is intended to be generated by a small Node.js helper in
    // `color.js/tools/contrast-fixtures.mjs`, which calls into Color.js
    // to compute the numeric parameters and expected results.
    let json = include_str!("contrast_fixtures.json");
    serde_json::from_str(json).expect("failed to parse contrast_fixtures.json")
}

fn approx_eq(a: f64, b: f64, eps: f64) -> bool {
    (a - b).abs() <= eps
}

#[test]
fn wcag21_matches_color_js() {
    let fixtures = fixtures();
    for case in fixtures.wcag21 {
        let actual = contrast_wcag21(case.y1, case.y2);
        assert!(
            approx_eq(actual, case.expect, 1e-6),
            "wcag21 mismatch: {:?}, got {actual}",
            case
        );
    }
}

#[test]
fn michelson_matches_color_js() {
    let fixtures = fixtures();
    for case in fixtures.michelson {
        let actual = contrast_michelson(case.y1, case.y2);
        assert!(
            approx_eq(actual, case.expect, 1e-6),
            "michelson mismatch: {:?}, got {actual}",
            case
        );
    }
}

#[test]
fn weber_matches_color_js() {
    let fixtures = fixtures();
    for case in fixtures.weber {
        let actual = contrast_weber(case.y1, case.y2);
        assert!(
            approx_eq(actual, case.expect, 1e-6),
            "weber mismatch: {:?}, got {actual}",
            case
        );
    }
}

#[test]
fn lstar_matches_color_js() {
    let fixtures = fixtures();
    for case in fixtures.lstar {
        let actual = contrast_lstar(case.l1, case.l2);
        assert!(
            approx_eq(actual, case.expect, 1e-6),
            "lstar mismatch: {:?}, got {actual}",
            case
        );
    }
}

#[test]
fn delta_phi_matches_color_js() {
    let fixtures = fixtures();
    for case in fixtures.delta_phi {
        let actual = contrast_delta_phi(case.l1, case.l2);
        assert!(
            approx_eq(actual, case.expect, 1e-6),
            "delta_phi mismatch: {:?}, got {actual}",
            case
        );
    }
}

#[test]
fn apca_matches_color_js() {
    let fixtures = fixtures();
    for case in fixtures.apca {
        let actual = contrast_apca_from_luminance(case.y_bg, case.y_txt);
        assert!(
            approx_eq(actual, case.expect, 1e-6),
            "apca mismatch: {:?}, got {actual}",
            case
        );
    }
}

